import { createServiceClient } from '@/lib/supabase/server'

const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token'
const GOOGLE_CALENDAR_API = 'https://www.googleapis.com/calendar/v3'

type TokenRow = {
  access_token: string
  refresh_token: string | null
  expires_at: string | null
  cogni_calendar_id: string | null
}

async function refreshGoogleToken(userId: string, row: TokenRow): Promise<string | null> {
  if (!row.refresh_token) return null

  const res = await fetch(GOOGLE_TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: process.env.GOOGLE_CALENDAR_CLIENT_ID!,
      client_secret: process.env.GOOGLE_CALENDAR_CLIENT_SECRET!,
      refresh_token: row.refresh_token,
      grant_type: 'refresh_token',
    }),
  })

  if (!res.ok) return null

  const data = await res.json()
  const expiresAt = new Date(Date.now() + data.expires_in * 1000).toISOString()

  const service = createServiceClient()
  await service
    .from('calendar_connections')
    .update({ access_token: data.access_token, expires_at: expiresAt, updated_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('provider', 'google')

  return data.access_token
}

async function getGoogleToken(userId: string): Promise<string | null> {
  const service = createServiceClient()
  const { data } = await service
    .from('calendar_connections')
    .select('access_token, refresh_token, expires_at, cogni_calendar_id')
    .eq('user_id', userId)
    .eq('provider', 'google')
    .single()

  if (!data) return null

  const expiry = data.expires_at ? new Date(data.expires_at).getTime() : 0
  const isExpired = expiry < Date.now() + 60_000

  if (isExpired) return refreshGoogleToken(userId, data)
  return data.access_token
}

async function getOrCreateCogniCalendar(token: string, userId: string): Promise<string | null> {
  const service = createServiceClient()

  // Check if we have it stored
  const { data } = await service
    .from('calendar_connections')
    .select('cogni_calendar_id')
    .eq('user_id', userId)
    .eq('provider', 'google')
    .single()

  if (data?.cogni_calendar_id) return data.cogni_calendar_id

  // Create it
  const res = await fetch(`${GOOGLE_CALENDAR_API}/calendars`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ summary: 'Cogni Study', description: 'Study blocks generated by Cogni' }),
  })

  if (!res.ok) {
    const body = await res.text()
    console.error('[calendar] failed to create calendar:', res.status, body)
    return null
  }

  const cal = await res.json()

  await service
    .from('calendar_connections')
    .update({ cogni_calendar_id: cal.id, updated_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('provider', 'google')

  return cal.id
}

export async function writeStudyBlocksToCalendar(
  userId: string,
  tasks: Array<{
    course_name: string
    duration_minutes: number
    order: number
  }>
): Promise<void> {
  const token = await getGoogleToken(userId)
  if (!token) { console.error('[calendar] no token for user', userId); return }

  const calendarId = await getOrCreateCogniCalendar(token, userId)
  if (!calendarId) { console.error('[calendar] could not get/create cogni calendar for user', userId); return }

  // Start blocks at 9am today, sequential
  const todayBase = new Date()
  todayBase.setHours(9, 0, 0, 0)
  let cursor = todayBase.getTime()

  for (const task of tasks.sort((a, b) => a.order - b.order)) {
    const start = new Date(cursor)
    const end = new Date(cursor + task.duration_minutes * 60_000)

    await fetch(`${GOOGLE_CALENDAR_API}/calendars/${encodeURIComponent(calendarId)}/events`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        summary: `Study: ${task.course_name}`,
        description: 'Generated by Cogni',
        start: { dateTime: start.toISOString() },
        end: { dateTime: end.toISOString() },
      }),
    })

    cursor = end.getTime() + 10 * 60_000 // 10 min break between blocks
  }
}

export async function getExistingEvents(
  userId: string,
  date: string
): Promise<Array<{ start: string; end: string; summary: string }>> {
  const token = await getGoogleToken(userId)
  if (!token) return []

  const timeMin = new Date(date + 'T00:00:00').toISOString()
  const timeMax = new Date(date + 'T23:59:59').toISOString()

  const res = await fetch(
    `${GOOGLE_CALENDAR_API}/calendars/primary/events?timeMin=${timeMin}&timeMax=${timeMax}&singleEvents=true`,
    { headers: { Authorization: `Bearer ${token}` } }
  )

  if (!res.ok) return []

  const data = await res.json()
  return (data.items ?? []).map((e: { summary?: string; start?: { dateTime?: string }; end?: { dateTime?: string } }) => ({
    summary: e.summary ?? '',
    start: e.start?.dateTime ?? '',
    end: e.end?.dateTime ?? '',
  }))
}

export async function isGoogleCalendarConnected(userId: string): Promise<boolean> {
  const service = createServiceClient()
  const { data } = await service
    .from('calendar_connections')
    .select('connection_id')
    .eq('user_id', userId)
    .eq('provider', 'google')
    .single()
  return !!data
}
